"""Initial migration with User, Client, and OAuth models

Revision ID: 41c15dd39005
Revises:
Create Date: 2025-07-12 21:00:00.123456

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "41c15dd39005"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The 'pass' statement is added because Alembic did not generate
    # any 'create_table' commands, only 'drop_table' commands which
    # we might not want to run on a fresh database.
    # If you want to create tables, you should delete this migration
    # file and your database, then run 'flask db migrate' again.
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # The 'pass' statement is added for the same reason.
    pass
    # ### end Alembic commands ###
